events { worker_connections 1024; }

http {
    upstream juiceshop {
        server juice-shop:3000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://juiceshop;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:;" always;

            add_header Access-Control-Allow-Origin "http://localhost" always;

            add_header X-Frame-Options "SAMEORIGIN" always;

            add_header X-Content-Type-Options "nosniff" always;
        }
    }
}