name: CI/CD pipeline of OWASP Juice Shop
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scans:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy SCA scan           # trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
      
      - name: Run Semgrep SAST scan       #Semgrep scan (SAST analysis)
        run: |
          python3 -m pip install semgrep
          semgrep scan --config=auto --error